

services:
  postgres:
    image: postgres:17
    container_name: pg-orders
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: L0_db
    ports:
      - "5432:5432"               
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ordersvc -d ordersvc_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"


volumes:
  pgdata:

