env: "local"

http_server: 
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s 

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres123"
  dbname: "L0_db"
  sslmode: "disable"

kafka:
  brokers: ["127.0.0.1:9092"]
  topic: "orders"
  group_id: "orderservice"
  dlq_topic: "orders-dlq"
  client_id: "orderservice"

cache:
  max_entries: 2000

log:
  level: "debug"
  format: "text"